server:
  port: 8480

spring:
  application:
    name: auth-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: auth-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000ms

  datasource:
    url: jdbc:mysql://localhost:3307/iot_device_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: "123456789"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  jackson:
    time-zone: Asia/Ho_Chi_Minh
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
    serialization:
      write-dates-as-timestamps: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

client:
  device:
    uri: http://device-service/api/v1

keycloak:
  auth-service-url: http://localhost:8082
  realm: lfs
  resource: quan_trac
  client-id: my-keycloak-client
  admin:                          # Đưa 'admin' ra cùng cấp với 'client-id' (thụt lề đúng 2 dấu cách)
    realm: master
    client-id: admin-cli
    username: admin
    password: password
  credentials:
    secret: WcLXOG0HHMxELj4BQtVD8ji4aHtD87nr
logging:
  level:
    org.keycloak.admin.client: DEBUG

