server:
  port: 8780
spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:mysql://localhost:3307/iot_notification_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: "123456789"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: localhost
    port: 1025
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false

#   Cấu hình Gmail cũ (Đã được comment lại để dùng Mailpit giả lập)
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: px.tien.2004@gmail.com
#    password: lpfoghmnorieaxwi
#    properties:
#      mail.smtp.auth: true
#      mail.smtp.starttls.enable: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

influxdb:
  url: http://localhost:8086
  org: iot_org
  bucket: telemetry_raw
  token: sK3zgZ73x_W4X4RHy5fvJEVzepz3IyEXfe9_dhoeg5yZ8W1vHuaUzLNavOld3UFzpitpqTJnr67KkwtwIIj9aA==

#logging:
#  level:
#    root: INFO
#    com.iot.notification: DEBUG
