listener 8883
# Đường dẫn tuyệt đối tới 3 file
cafile F:/TIEN_LFS/QuanTrac/mosquitto/certs/ca.crt
certfile F:/TIEN_LFS/QuanTrac/mosquitto/certs/server.crt
keyfile F:/TIEN_LFS/QuanTrac/mosquitto/certs/server.key

# Bật tính năng bắt buộc Client phải trình chứng chỉ (Mức 3)
require_certificate true

# Bảo mật mã hóa
tls_version tlsv1.2