server:
  port: 8180 # Cổng chạy Gateway công cộng trên máy vật lý

spring:
  application:
    name: gateway-service
  data:
    redis:
      host: localhost # Kết nối tới cổng Redis của Docker map ra máy thật
      port: 6379
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # Áp dụng cho tất cả các đường dẫn API
            allowedOrigins: "http://localhost:3000" # URL của trang Frontend (Thay bằng domain production khi deploy)
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*" # Cho phép FE gửi lên mọi loại Header (Authorization, Content-Type, v.v.)
            allowCredentials: true # Bắt buộc phải là 'true' nếu FE có gửi Cookie hoặc dùng TokenRelay
            maxAge: 3600 # Cache cấu hình CORS này trong 1 tiếng để tránh FE phải gửi request OPTIONS liên tục
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: device-service
          uri: lb://device-service
          predicates:
            - Path=/api/v1/stations/**,/api/v1/sensors/**,/api/v1/sensor-types/**, /api/v1/gateways/**
          filters:
            - TokenRelay
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@ipKeyResolver}"

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - TokenRelay
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@ipKeyResolver}"

        - id: user-service
          uri:
            lb://user-service
          predicates:
            - Path=/api/v1/user/**
          filters:
            - TokenRelay
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@ipKeyResolver}"

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8082/realms/iot-realm/protocol/openid-connect/certs
          issuer-uri:

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/