server:
  port: 8180 # Cổng chạy Gateway công cộng trên máy vật lý

spring:
  application:
    name: gateway-service
  data:
    redis:
      host: localhost # Kết nối tới cổng Redis của Docker map ra máy thật
      port: 6379
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # Áp dụng cho tất cả các đường dẫn API
            allowedOrigins:
              - "http://localhost:3000" # URL của trang Frontend React
              - "http://localhost:4200" # URL của trang Frontend Angular
              - "http://localhost:5173" # URL của trang Frontend Vite mới
              - "http://localhost:5174"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*" # Cho phép FE gửi lên mọi loại Header (Authorization, Content-Type, v.v.)
            allowCredentials: true # Bắt buộc phải là 'true' nếu FE có gửi Cookie hoặc dùng TokenRelay
            maxAge: 3600 # Cache cấu hình CORS này trong 1 tiếng để tránh FE phải gửi request OPTIONS liên tục
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      routes:
        - id: device-service
          uri: lb://device-service
          predicates:
            - Path=/api/v1/stations/**,/api/v1/sensors/**,/api/v1/sensor-types/**,/api/v1/gateways/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@ipKeyResolver}"

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@ipKeyResolver}"

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user/**,/api/v1/users/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@ipKeyResolver}"

        - id: realtime-service-ws
          uri: lb:ws://realtime-service
          predicates:
            - Path=/ws/telemetry/**

        - id: realtime-service
          uri: lb://realtime-service
          predicates:
            - Path=/api/v1/telemetry/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@ipKeyResolver}"

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8082/realms/lfs/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/