server:
  port: 8380

spring:
  application:
    name: ingestion-service

mqtt:
  url: tcp://localhost:1883
  client-id: spring_boot_ingestion_client
  topic: iot/telemetry/#
  completion-timeout: 5000

client:
  device:
    uri: http://device-service/api/v1